site_name: VelociRaptoR-K
site_description: Сайт-портфолио с лабораторными работами и достижениями
site_author: Быстров Николай
docs_dir: docs
site_dir: ../docs

theme:
  name: material
  language: ru
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Переключить на темную тему
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Переключить на светлую тему
  features:
    - navigation.sections
    - navigation.expand
    - toc.sidebar
    - content.code.copy

nav:
  - Главная страница: index.md
  - Об авторе: about.md
  - Лабораторные работы:
      - Лабораторная работа 9: labs/Laboratory_9.md
      - Лабораторная работа 10: labs/Laboratory_10.md
      - Лабораторная по NumPy: labs/LR-2.md
  - Место учёбы: education.md
  - Контакты: contacts.md
  - Увлечения: hobbies.md

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.highlight:
        use_pygments: true
  - toc:
      permalink: true
      toc_depth: 0
