# Название сайта
site_name: VelociRaptoR-K
site_description: Сайт-портфолио с лабораторными работами и достижениями
site_author: Быстров Николай
docs_dir: docs
site_dir: ../docs

# Настройка темы Windmill
theme:
  name: windmill
  language: ru
  palette:
    # Цветовая схема
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Переключить на темную тему
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Переключить на светлую тему
  features:
    - navigation.sections  # Показывает секции навигации
    - navigation.expand    # Раскрывает все разделы по умолчанию
    - toc.sidebar          # оглавление справа

# Структура меню (навигация)
nav:
  - Главная страница: index.md
  - Об авторе: about.md
  - Лабораторные работы:
      - Лабораторная работа 9: labs/Laboratory_9.md
      - Лабораторная работа 10: labs/Laboratory_10.md
      - Лабораторная по NumPy: labs/LR-2.md
  - Место учёбы: education.md
  - Контакты: contacts.md
  - Увлечения: hobbies.md

# Дополнительные настройки
plugins:
  - search # добавили поиск на сайте

markdown_extensions:
  - admonition # позволяет создавать красивые блоки с заметками, предупреждениями
  - codehilite # делает код цветным
  - toc:
      permalink: true # добавляет символ ¶ рядом с заголовками, при клике на который можно скопировать прямую ссылку на этот заголовок
      toc_depth: 0

